# Generated by Django 3.0.4 on 2020-04-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200410_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, db_index=True)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.CharField(db_index=True, max_length=150)),
                ('user_id', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='MessageChat',
        ),
    ]
