# Generated by Django 3.0.4 on 2020-04-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200411_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=150)),
                ('user_id', models.CharField(db_index=True, max_length=150)),
                ('status', models.CharField(db_index=True, max_length=150)),
                ('friends', models.CharField(db_index=True, max_length=150)),
                ('profile_id', models.CharField(db_index=True, max_length=150)),
            ],
        ),
    ]
