# Generated by Django 3.0.4 on 2020-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=150)),
                ('user_id', models.CharField(db_index=True, max_length=150)),
                ('friend_id', models.CharField(db_index=True, max_length=150)),
            ],
        ),
    ]
